#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="music")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertmic_favourite_song(mic_favourite_song instance);
    partial void Updatemic_favourite_song(mic_favourite_song instance);
    partial void Deletemic_favourite_song(mic_favourite_song instance);
    partial void Insertmic_playlist(mic_playlist instance);
    partial void Updatemic_playlist(mic_playlist instance);
    partial void Deletemic_playlist(mic_playlist instance);
    partial void Insertmic_singer(mic_singer instance);
    partial void Updatemic_singer(mic_singer instance);
    partial void Deletemic_singer(mic_singer instance);
    partial void Insertmic_song_comment(mic_song_comment instance);
    partial void Updatemic_song_comment(mic_song_comment instance);
    partial void Deletemic_song_comment(mic_song_comment instance);
    partial void Insertmic_song_like(mic_song_like instance);
    partial void Updatemic_song_like(mic_song_like instance);
    partial void Deletemic_song_like(mic_song_like instance);
    partial void Insertmic_song_playlist(mic_song_playlist instance);
    partial void Updatemic_song_playlist(mic_song_playlist instance);
    partial void Deletemic_song_playlist(mic_song_playlist instance);
    partial void Insertmic_song_singer(mic_song_singer instance);
    partial void Updatemic_song_singer(mic_song_singer instance);
    partial void Deletemic_song_singer(mic_song_singer instance);
    partial void Insertmic_song(mic_song instance);
    partial void Updatemic_song(mic_song instance);
    partial void Deletemic_song(mic_song instance);
    partial void Insertmic_user(mic_user instance);
    partial void Updatemic_user(mic_user instance);
    partial void Deletemic_user(mic_user instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<mic_favourite_song> mic_favourite_songs
		{
			get
			{
				return this.GetTable<mic_favourite_song>();
			}
		}
		
		public System.Data.Linq.Table<mic_playlist> mic_playlists
		{
			get
			{
				return this.GetTable<mic_playlist>();
			}
		}
		
		public System.Data.Linq.Table<mic_singer> mic_singers
		{
			get
			{
				return this.GetTable<mic_singer>();
			}
		}
		
		public System.Data.Linq.Table<mic_song_comment> mic_song_comments
		{
			get
			{
				return this.GetTable<mic_song_comment>();
			}
		}
		
		public System.Data.Linq.Table<mic_song_like> mic_song_likes
		{
			get
			{
				return this.GetTable<mic_song_like>();
			}
		}
		
		public System.Data.Linq.Table<mic_song_playlist> mic_song_playlists
		{
			get
			{
				return this.GetTable<mic_song_playlist>();
			}
		}
		
		public System.Data.Linq.Table<mic_song_singer> mic_song_singers
		{
			get
			{
				return this.GetTable<mic_song_singer>();
			}
		}
		
		public System.Data.Linq.Table<mic_song> mic_songs
		{
			get
			{
				return this.GetTable<mic_song>();
			}
		}
		
		public System.Data.Linq.Table<mic_user> mic_users
		{
			get
			{
				return this.GetTable<mic_user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_favourite_songs")]
	public partial class mic_favourite_song : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _favourite_song_id;
		
		private System.Nullable<int> _song_id;
		
		private System.Nullable<int> _user_id;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private EntityRef<mic_song> _mic_song;
		
		private EntityRef<mic_user> _mic_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfavourite_song_idChanging(int value);
    partial void Onfavourite_song_idChanged();
    partial void Onsong_idChanging(System.Nullable<int> value);
    partial void Onsong_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    #endregion
		
		public mic_favourite_song()
		{
			this._mic_song = default(EntityRef<mic_song>);
			this._mic_user = default(EntityRef<mic_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_favourite_song_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int favourite_song_id
		{
			get
			{
				return this._favourite_song_id;
			}
			set
			{
				if ((this._favourite_song_id != value))
				{
					this.Onfavourite_song_idChanging(value);
					this.SendPropertyChanging();
					this._favourite_song_id = value;
					this.SendPropertyChanged("favourite_song_id");
					this.Onfavourite_song_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_id", DbType="Int")]
		public System.Nullable<int> song_id
		{
			get
			{
				return this._song_id;
			}
			set
			{
				if ((this._song_id != value))
				{
					if (this._mic_song.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsong_idChanging(value);
					this.SendPropertyChanging();
					this._song_id = value;
					this.SendPropertyChanged("song_id");
					this.Onsong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._mic_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_favourite_song", Storage="_mic_song", ThisKey="song_id", OtherKey="song_id", IsForeignKey=true)]
		public mic_song mic_song
		{
			get
			{
				return this._mic_song.Entity;
			}
			set
			{
				mic_song previousValue = this._mic_song.Entity;
				if (((previousValue != value) 
							|| (this._mic_song.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_song.Entity = null;
						previousValue.mic_favourite_songs.Remove(this);
					}
					this._mic_song.Entity = value;
					if ((value != null))
					{
						value.mic_favourite_songs.Add(this);
						this._song_id = value.song_id;
					}
					else
					{
						this._song_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("mic_song");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_user_mic_favourite_song", Storage="_mic_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public mic_user mic_user
		{
			get
			{
				return this._mic_user.Entity;
			}
			set
			{
				mic_user previousValue = this._mic_user.Entity;
				if (((previousValue != value) 
							|| (this._mic_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_user.Entity = null;
						previousValue.mic_favourite_songs.Remove(this);
					}
					this._mic_user.Entity = value;
					if ((value != null))
					{
						value.mic_favourite_songs.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("mic_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_playlists")]
	public partial class mic_playlist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _playlist_id;
		
		private string _name;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private EntitySet<mic_song_playlist> _mic_song_playlists;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplaylist_idChanging(int value);
    partial void Onplaylist_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    #endregion
		
		public mic_playlist()
		{
			this._mic_song_playlists = new EntitySet<mic_song_playlist>(new Action<mic_song_playlist>(this.attach_mic_song_playlists), new Action<mic_song_playlist>(this.detach_mic_song_playlists));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playlist_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int playlist_id
		{
			get
			{
				return this._playlist_id;
			}
			set
			{
				if ((this._playlist_id != value))
				{
					this.Onplaylist_idChanging(value);
					this.SendPropertyChanging();
					this._playlist_id = value;
					this.SendPropertyChanged("playlist_id");
					this.Onplaylist_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_playlist_mic_song_playlist", Storage="_mic_song_playlists", ThisKey="playlist_id", OtherKey="playlist_id")]
		public EntitySet<mic_song_playlist> mic_song_playlists
		{
			get
			{
				return this._mic_song_playlists;
			}
			set
			{
				this._mic_song_playlists.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_mic_song_playlists(mic_song_playlist entity)
		{
			this.SendPropertyChanging();
			entity.mic_playlist = this;
		}
		
		private void detach_mic_song_playlists(mic_song_playlist entity)
		{
			this.SendPropertyChanging();
			entity.mic_playlist = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_singers")]
	public partial class mic_singer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _singer_id;
		
		private string _name;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private EntitySet<mic_song_singer> _mic_song_singers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsinger_idChanging(int value);
    partial void Onsinger_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    #endregion
		
		public mic_singer()
		{
			this._mic_song_singers = new EntitySet<mic_song_singer>(new Action<mic_song_singer>(this.attach_mic_song_singers), new Action<mic_song_singer>(this.detach_mic_song_singers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int singer_id
		{
			get
			{
				return this._singer_id;
			}
			set
			{
				if ((this._singer_id != value))
				{
					this.Onsinger_idChanging(value);
					this.SendPropertyChanging();
					this._singer_id = value;
					this.SendPropertyChanged("singer_id");
					this.Onsinger_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_singer_mic_song_singer", Storage="_mic_song_singers", ThisKey="singer_id", OtherKey="singer_id")]
		public EntitySet<mic_song_singer> mic_song_singers
		{
			get
			{
				return this._mic_song_singers;
			}
			set
			{
				this._mic_song_singers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_mic_song_singers(mic_song_singer entity)
		{
			this.SendPropertyChanging();
			entity.mic_singer = this;
		}
		
		private void detach_mic_song_singers(mic_song_singer entity)
		{
			this.SendPropertyChanging();
			entity.mic_singer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_song_comments")]
	public partial class mic_song_comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _song_comment_id;
		
		private int _song_id;
		
		private int _user_id;
		
		private string _comment;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private EntityRef<mic_song> _mic_song;
		
		private EntityRef<mic_user> _mic_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsong_comment_idChanging(int value);
    partial void Onsong_comment_idChanged();
    partial void Onsong_idChanging(int value);
    partial void Onsong_idChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    #endregion
		
		public mic_song_comment()
		{
			this._mic_song = default(EntityRef<mic_song>);
			this._mic_user = default(EntityRef<mic_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_comment_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int song_comment_id
		{
			get
			{
				return this._song_comment_id;
			}
			set
			{
				if ((this._song_comment_id != value))
				{
					this.Onsong_comment_idChanging(value);
					this.SendPropertyChanging();
					this._song_comment_id = value;
					this.SendPropertyChanged("song_comment_id");
					this.Onsong_comment_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_id", DbType="Int NOT NULL")]
		public int song_id
		{
			get
			{
				return this._song_id;
			}
			set
			{
				if ((this._song_id != value))
				{
					if (this._mic_song.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsong_idChanging(value);
					this.SendPropertyChanging();
					this._song_id = value;
					this.SendPropertyChanged("song_id");
					this.Onsong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._mic_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_comment", Storage="_mic_song", ThisKey="song_id", OtherKey="song_id", IsForeignKey=true)]
		public mic_song mic_song
		{
			get
			{
				return this._mic_song.Entity;
			}
			set
			{
				mic_song previousValue = this._mic_song.Entity;
				if (((previousValue != value) 
							|| (this._mic_song.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_song.Entity = null;
						previousValue.mic_song_comments.Remove(this);
					}
					this._mic_song.Entity = value;
					if ((value != null))
					{
						value.mic_song_comments.Add(this);
						this._song_id = value.song_id;
					}
					else
					{
						this._song_id = default(int);
					}
					this.SendPropertyChanged("mic_song");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_user_mic_song_comment", Storage="_mic_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public mic_user mic_user
		{
			get
			{
				return this._mic_user.Entity;
			}
			set
			{
				mic_user previousValue = this._mic_user.Entity;
				if (((previousValue != value) 
							|| (this._mic_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_user.Entity = null;
						previousValue.mic_song_comments.Remove(this);
					}
					this._mic_user.Entity = value;
					if ((value != null))
					{
						value.mic_song_comments.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(int);
					}
					this.SendPropertyChanged("mic_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_song_likes")]
	public partial class mic_song_like : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _song_like_id;
		
		private int _song_id;
		
		private int _user_id;
		
		private bool _liked;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private EntityRef<mic_song> _mic_song;
		
		private EntityRef<mic_user> _mic_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsong_like_idChanging(int value);
    partial void Onsong_like_idChanged();
    partial void Onsong_idChanging(int value);
    partial void Onsong_idChanged();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void OnlikedChanging(bool value);
    partial void OnlikedChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    #endregion
		
		public mic_song_like()
		{
			this._mic_song = default(EntityRef<mic_song>);
			this._mic_user = default(EntityRef<mic_user>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_like_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int song_like_id
		{
			get
			{
				return this._song_like_id;
			}
			set
			{
				if ((this._song_like_id != value))
				{
					this.Onsong_like_idChanging(value);
					this.SendPropertyChanging();
					this._song_like_id = value;
					this.SendPropertyChanged("song_like_id");
					this.Onsong_like_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_id", DbType="Int NOT NULL")]
		public int song_id
		{
			get
			{
				return this._song_id;
			}
			set
			{
				if ((this._song_id != value))
				{
					if (this._mic_song.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsong_idChanging(value);
					this.SendPropertyChanging();
					this._song_id = value;
					this.SendPropertyChanged("song_id");
					this.Onsong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL")]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._mic_user.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liked", DbType="Bit NOT NULL")]
		public bool liked
		{
			get
			{
				return this._liked;
			}
			set
			{
				if ((this._liked != value))
				{
					this.OnlikedChanging(value);
					this.SendPropertyChanging();
					this._liked = value;
					this.SendPropertyChanged("liked");
					this.OnlikedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_like", Storage="_mic_song", ThisKey="song_id", OtherKey="song_id", IsForeignKey=true)]
		public mic_song mic_song
		{
			get
			{
				return this._mic_song.Entity;
			}
			set
			{
				mic_song previousValue = this._mic_song.Entity;
				if (((previousValue != value) 
							|| (this._mic_song.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_song.Entity = null;
						previousValue.mic_song_likes.Remove(this);
					}
					this._mic_song.Entity = value;
					if ((value != null))
					{
						value.mic_song_likes.Add(this);
						this._song_id = value.song_id;
					}
					else
					{
						this._song_id = default(int);
					}
					this.SendPropertyChanged("mic_song");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_user_mic_song_like", Storage="_mic_user", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public mic_user mic_user
		{
			get
			{
				return this._mic_user.Entity;
			}
			set
			{
				mic_user previousValue = this._mic_user.Entity;
				if (((previousValue != value) 
							|| (this._mic_user.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_user.Entity = null;
						previousValue.mic_song_likes.Remove(this);
					}
					this._mic_user.Entity = value;
					if ((value != null))
					{
						value.mic_song_likes.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(int);
					}
					this.SendPropertyChanged("mic_user");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_song_playlists")]
	public partial class mic_song_playlist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _song_playlist_id;
		
		private System.Nullable<int> _song_id;
		
		private System.Nullable<int> _playlist_id;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private EntityRef<mic_playlist> _mic_playlist;
		
		private EntityRef<mic_song> _mic_song;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsong_playlist_idChanging(int value);
    partial void Onsong_playlist_idChanged();
    partial void Onsong_idChanging(System.Nullable<int> value);
    partial void Onsong_idChanged();
    partial void Onplaylist_idChanging(System.Nullable<int> value);
    partial void Onplaylist_idChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    #endregion
		
		public mic_song_playlist()
		{
			this._mic_playlist = default(EntityRef<mic_playlist>);
			this._mic_song = default(EntityRef<mic_song>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_playlist_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int song_playlist_id
		{
			get
			{
				return this._song_playlist_id;
			}
			set
			{
				if ((this._song_playlist_id != value))
				{
					this.Onsong_playlist_idChanging(value);
					this.SendPropertyChanging();
					this._song_playlist_id = value;
					this.SendPropertyChanged("song_playlist_id");
					this.Onsong_playlist_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_id", DbType="Int")]
		public System.Nullable<int> song_id
		{
			get
			{
				return this._song_id;
			}
			set
			{
				if ((this._song_id != value))
				{
					if (this._mic_song.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsong_idChanging(value);
					this.SendPropertyChanging();
					this._song_id = value;
					this.SendPropertyChanged("song_id");
					this.Onsong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playlist_id", DbType="Int")]
		public System.Nullable<int> playlist_id
		{
			get
			{
				return this._playlist_id;
			}
			set
			{
				if ((this._playlist_id != value))
				{
					if (this._mic_playlist.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onplaylist_idChanging(value);
					this.SendPropertyChanging();
					this._playlist_id = value;
					this.SendPropertyChanged("playlist_id");
					this.Onplaylist_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_playlist_mic_song_playlist", Storage="_mic_playlist", ThisKey="playlist_id", OtherKey="playlist_id", IsForeignKey=true)]
		public mic_playlist mic_playlist
		{
			get
			{
				return this._mic_playlist.Entity;
			}
			set
			{
				mic_playlist previousValue = this._mic_playlist.Entity;
				if (((previousValue != value) 
							|| (this._mic_playlist.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_playlist.Entity = null;
						previousValue.mic_song_playlists.Remove(this);
					}
					this._mic_playlist.Entity = value;
					if ((value != null))
					{
						value.mic_song_playlists.Add(this);
						this._playlist_id = value.playlist_id;
					}
					else
					{
						this._playlist_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("mic_playlist");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_playlist", Storage="_mic_song", ThisKey="song_id", OtherKey="song_id", IsForeignKey=true)]
		public mic_song mic_song
		{
			get
			{
				return this._mic_song.Entity;
			}
			set
			{
				mic_song previousValue = this._mic_song.Entity;
				if (((previousValue != value) 
							|| (this._mic_song.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_song.Entity = null;
						previousValue.mic_song_playlists.Remove(this);
					}
					this._mic_song.Entity = value;
					if ((value != null))
					{
						value.mic_song_playlists.Add(this);
						this._song_id = value.song_id;
					}
					else
					{
						this._song_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("mic_song");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_song_singers")]
	public partial class mic_song_singer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _song_singer_id;
		
		private System.Nullable<int> _song_id;
		
		private System.Nullable<int> _singer_id;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private EntityRef<mic_singer> _mic_singer;
		
		private EntityRef<mic_song> _mic_song;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsong_singer_idChanging(int value);
    partial void Onsong_singer_idChanged();
    partial void Onsong_idChanging(System.Nullable<int> value);
    partial void Onsong_idChanged();
    partial void Onsinger_idChanging(System.Nullable<int> value);
    partial void Onsinger_idChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    #endregion
		
		public mic_song_singer()
		{
			this._mic_singer = default(EntityRef<mic_singer>);
			this._mic_song = default(EntityRef<mic_song>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_singer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int song_singer_id
		{
			get
			{
				return this._song_singer_id;
			}
			set
			{
				if ((this._song_singer_id != value))
				{
					this.Onsong_singer_idChanging(value);
					this.SendPropertyChanging();
					this._song_singer_id = value;
					this.SendPropertyChanged("song_singer_id");
					this.Onsong_singer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_id", DbType="Int")]
		public System.Nullable<int> song_id
		{
			get
			{
				return this._song_id;
			}
			set
			{
				if ((this._song_id != value))
				{
					if (this._mic_song.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsong_idChanging(value);
					this.SendPropertyChanging();
					this._song_id = value;
					this.SendPropertyChanged("song_id");
					this.Onsong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_singer_id", DbType="Int")]
		public System.Nullable<int> singer_id
		{
			get
			{
				return this._singer_id;
			}
			set
			{
				if ((this._singer_id != value))
				{
					if (this._mic_singer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsinger_idChanging(value);
					this.SendPropertyChanging();
					this._singer_id = value;
					this.SendPropertyChanged("singer_id");
					this.Onsinger_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_singer_mic_song_singer", Storage="_mic_singer", ThisKey="singer_id", OtherKey="singer_id", IsForeignKey=true)]
		public mic_singer mic_singer
		{
			get
			{
				return this._mic_singer.Entity;
			}
			set
			{
				mic_singer previousValue = this._mic_singer.Entity;
				if (((previousValue != value) 
							|| (this._mic_singer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_singer.Entity = null;
						previousValue.mic_song_singers.Remove(this);
					}
					this._mic_singer.Entity = value;
					if ((value != null))
					{
						value.mic_song_singers.Add(this);
						this._singer_id = value.singer_id;
					}
					else
					{
						this._singer_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("mic_singer");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_singer", Storage="_mic_song", ThisKey="song_id", OtherKey="song_id", IsForeignKey=true)]
		public mic_song mic_song
		{
			get
			{
				return this._mic_song.Entity;
			}
			set
			{
				mic_song previousValue = this._mic_song.Entity;
				if (((previousValue != value) 
							|| (this._mic_song.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._mic_song.Entity = null;
						previousValue.mic_song_singers.Remove(this);
					}
					this._mic_song.Entity = value;
					if ((value != null))
					{
						value.mic_song_singers.Add(this);
						this._song_id = value.song_id;
					}
					else
					{
						this._song_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("mic_song");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_songs")]
	public partial class mic_song : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _song_id;
		
		private string _code;
		
		private string _name;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private string _note;
		
		private EntitySet<mic_favourite_song> _mic_favourite_songs;
		
		private EntitySet<mic_song_comment> _mic_song_comments;
		
		private EntitySet<mic_song_like> _mic_song_likes;
		
		private EntitySet<mic_song_playlist> _mic_song_playlists;
		
		private EntitySet<mic_song_singer> _mic_song_singers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsong_idChanging(int value);
    partial void Onsong_idChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    #endregion
		
		public mic_song()
		{
			this._mic_favourite_songs = new EntitySet<mic_favourite_song>(new Action<mic_favourite_song>(this.attach_mic_favourite_songs), new Action<mic_favourite_song>(this.detach_mic_favourite_songs));
			this._mic_song_comments = new EntitySet<mic_song_comment>(new Action<mic_song_comment>(this.attach_mic_song_comments), new Action<mic_song_comment>(this.detach_mic_song_comments));
			this._mic_song_likes = new EntitySet<mic_song_like>(new Action<mic_song_like>(this.attach_mic_song_likes), new Action<mic_song_like>(this.detach_mic_song_likes));
			this._mic_song_playlists = new EntitySet<mic_song_playlist>(new Action<mic_song_playlist>(this.attach_mic_song_playlists), new Action<mic_song_playlist>(this.detach_mic_song_playlists));
			this._mic_song_singers = new EntitySet<mic_song_singer>(new Action<mic_song_singer>(this.attach_mic_song_singers), new Action<mic_song_singer>(this.detach_mic_song_singers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_song_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int song_id
		{
			get
			{
				return this._song_id;
			}
			set
			{
				if ((this._song_id != value))
				{
					this.Onsong_idChanging(value);
					this.SendPropertyChanging();
					this._song_id = value;
					this.SendPropertyChanged("song_id");
					this.Onsong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(255)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(255)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_favourite_song", Storage="_mic_favourite_songs", ThisKey="song_id", OtherKey="song_id")]
		public EntitySet<mic_favourite_song> mic_favourite_songs
		{
			get
			{
				return this._mic_favourite_songs;
			}
			set
			{
				this._mic_favourite_songs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_comment", Storage="_mic_song_comments", ThisKey="song_id", OtherKey="song_id")]
		public EntitySet<mic_song_comment> mic_song_comments
		{
			get
			{
				return this._mic_song_comments;
			}
			set
			{
				this._mic_song_comments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_like", Storage="_mic_song_likes", ThisKey="song_id", OtherKey="song_id")]
		public EntitySet<mic_song_like> mic_song_likes
		{
			get
			{
				return this._mic_song_likes;
			}
			set
			{
				this._mic_song_likes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_playlist", Storage="_mic_song_playlists", ThisKey="song_id", OtherKey="song_id")]
		public EntitySet<mic_song_playlist> mic_song_playlists
		{
			get
			{
				return this._mic_song_playlists;
			}
			set
			{
				this._mic_song_playlists.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_song_mic_song_singer", Storage="_mic_song_singers", ThisKey="song_id", OtherKey="song_id")]
		public EntitySet<mic_song_singer> mic_song_singers
		{
			get
			{
				return this._mic_song_singers;
			}
			set
			{
				this._mic_song_singers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_mic_favourite_songs(mic_favourite_song entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = this;
		}
		
		private void detach_mic_favourite_songs(mic_favourite_song entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = null;
		}
		
		private void attach_mic_song_comments(mic_song_comment entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = this;
		}
		
		private void detach_mic_song_comments(mic_song_comment entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = null;
		}
		
		private void attach_mic_song_likes(mic_song_like entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = this;
		}
		
		private void detach_mic_song_likes(mic_song_like entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = null;
		}
		
		private void attach_mic_song_playlists(mic_song_playlist entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = this;
		}
		
		private void detach_mic_song_playlists(mic_song_playlist entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = null;
		}
		
		private void attach_mic_song_singers(mic_song_singer entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = this;
		}
		
		private void detach_mic_song_singers(mic_song_singer entity)
		{
			this.SendPropertyChanging();
			entity.mic_song = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_users")]
	public partial class mic_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _login_name;
		
		private string _full_name;
		
		private string _email;
		
		private string _mobile_number;
		
		private string _password;
		
		private string _role;
		
		private char _is_deleted;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _created_time;
		
		private string _modified_by;
		
		private System.Nullable<System.DateTime> _modified_time;
		
		private EntitySet<mic_favourite_song> _mic_favourite_songs;
		
		private EntitySet<mic_song_comment> _mic_song_comments;
		
		private EntitySet<mic_song_like> _mic_song_likes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onlogin_nameChanging(string value);
    partial void Onlogin_nameChanged();
    partial void Onfull_nameChanging(string value);
    partial void Onfull_nameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onmobile_numberChanging(string value);
    partial void Onmobile_numberChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void Onis_deletedChanging(char value);
    partial void Onis_deletedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Oncreated_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_timeChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onmodified_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onmodified_timeChanged();
    #endregion
		
		public mic_user()
		{
			this._mic_favourite_songs = new EntitySet<mic_favourite_song>(new Action<mic_favourite_song>(this.attach_mic_favourite_songs), new Action<mic_favourite_song>(this.detach_mic_favourite_songs));
			this._mic_song_comments = new EntitySet<mic_song_comment>(new Action<mic_song_comment>(this.attach_mic_song_comments), new Action<mic_song_comment>(this.detach_mic_song_comments));
			this._mic_song_likes = new EntitySet<mic_song_like>(new Action<mic_song_like>(this.attach_mic_song_likes), new Action<mic_song_like>(this.detach_mic_song_likes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_name", DbType="NVarChar(255)")]
		public string login_name
		{
			get
			{
				return this._login_name;
			}
			set
			{
				if ((this._login_name != value))
				{
					this.Onlogin_nameChanging(value);
					this.SendPropertyChanging();
					this._login_name = value;
					this.SendPropertyChanged("login_name");
					this.Onlogin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_full_name", DbType="NVarChar(255)")]
		public string full_name
		{
			get
			{
				return this._full_name;
			}
			set
			{
				if ((this._full_name != value))
				{
					this.Onfull_nameChanging(value);
					this.SendPropertyChanging();
					this._full_name = value;
					this.SendPropertyChanged("full_name");
					this.Onfull_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_number", DbType="NVarChar(20)")]
		public string mobile_number
		{
			get
			{
				return this._mobile_number;
			}
			set
			{
				if ((this._mobile_number != value))
				{
					this.Onmobile_numberChanging(value);
					this.SendPropertyChanging();
					this._mobile_number = value;
					this.SendPropertyChanged("mobile_number");
					this.Onmobile_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(255)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NVarChar(50)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Char(1) NOT NULL")]
		public char is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_time
		{
			get
			{
				return this._created_time;
			}
			set
			{
				if ((this._created_time != value))
				{
					this.Oncreated_timeChanging(value);
					this.SendPropertyChanging();
					this._created_time = value;
					this.SendPropertyChanged("created_time");
					this.Oncreated_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(50)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified_time
		{
			get
			{
				return this._modified_time;
			}
			set
			{
				if ((this._modified_time != value))
				{
					this.Onmodified_timeChanging(value);
					this.SendPropertyChanging();
					this._modified_time = value;
					this.SendPropertyChanged("modified_time");
					this.Onmodified_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_user_mic_favourite_song", Storage="_mic_favourite_songs", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<mic_favourite_song> mic_favourite_songs
		{
			get
			{
				return this._mic_favourite_songs;
			}
			set
			{
				this._mic_favourite_songs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_user_mic_song_comment", Storage="_mic_song_comments", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<mic_song_comment> mic_song_comments
		{
			get
			{
				return this._mic_song_comments;
			}
			set
			{
				this._mic_song_comments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="mic_user_mic_song_like", Storage="_mic_song_likes", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<mic_song_like> mic_song_likes
		{
			get
			{
				return this._mic_song_likes;
			}
			set
			{
				this._mic_song_likes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_mic_favourite_songs(mic_favourite_song entity)
		{
			this.SendPropertyChanging();
			entity.mic_user = this;
		}
		
		private void detach_mic_favourite_songs(mic_favourite_song entity)
		{
			this.SendPropertyChanging();
			entity.mic_user = null;
		}
		
		private void attach_mic_song_comments(mic_song_comment entity)
		{
			this.SendPropertyChanging();
			entity.mic_user = this;
		}
		
		private void detach_mic_song_comments(mic_song_comment entity)
		{
			this.SendPropertyChanging();
			entity.mic_user = null;
		}
		
		private void attach_mic_song_likes(mic_song_like entity)
		{
			this.SendPropertyChanging();
			entity.mic_user = this;
		}
		
		private void detach_mic_song_likes(mic_song_like entity)
		{
			this.SendPropertyChanging();
			entity.mic_user = null;
		}
	}
}
#pragma warning restore 1591
